#!/usr/bin/env python3
from argparse import ArgumentParser
import sqlite3


def main():
    cli_parser = ArgumentParser()
    cli_parser.add_argument('--database', '-d', required=True)
    cli_parser.add_argument('--query-id', '-q', required=True)
    cli_configure = cli_parser.parse_args()
    db = sqlite3.connect(cli_configure.database)
    query_id = cli_configure.query_id
    cursor = db.execute('select `profile` from `profile` where query_id=? limit 1', (query_id, ))
    row = cursor.fetchone()
    profile = row[0]
    filename = f'raw-{query_id.replace(":", "")}.txt'
    with open(filename, 'w', encoding='utf8') as fd:
        fd.write(profile)


if __name__ == '__main__':
    main()
