#!/bin/bash
DATABASE_FILENAME="$1"
QUERY_ID="$2"


function print_help() {
  cat <<'EOF'
./dump_profile_sqlite $SQLITE_FILENAME $QUERY_ID

EOF
}


if [[ -z "${DATABASE_FILENAME}" ]] || [[ ! -f "${DATABASE_FILENAME}" ]];then
  echo "\$1 should be a valid database file"
  print_help
  exit 0
fi


if [[ -z "${QUERY_ID}" ]];then
  echo "\$2 should be a valid query id"
  print_help
  exit 0
fi


sqlite3 "${DATABASE_FILENAME}" <<EOF
SELECT \`profile\` FROM \`profile\`
WHERE query_id='${QUERY_ID}'
limit 1
EOF

